# Generated by Django 4.0.6 on 2022-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
