# Generated by Django 4.0.6 on 2022-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
